spring:
  application:
    name: technology-service
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:technology_db}
    username: ${DB_USER:tech_user}
    password: ${DB_PASSWORD:tech_pass}
  webflux:
    base-path: /api/v1

server:
  port: ${SERVER_PORT:8081}

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Actuator / Health / Metrics / Tracing
management:
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY:0.1}
    baggage:
      correlation:
        fields:
          - messageId
          - x-message-id
      remote-fields: messageId,x-message-id
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers,prometheus
      base-path: /
      path-mapping:
        health: actuator/health
        metrics: actuator/metrics
        loggers: ${spring.application.name}/actuator/loggers
  endpoint:
    health:
      probes:
        enabled: false
      show-details: "always"
  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: false
    r2dbc:
      enabled: true
    ping:
      enabled: false
    refresh:
      enabled: false

# Example external client (optional)
email-validator:
  base-url: "${EMAIL_VALIDATOR_BASE_URL:https://emailvalidation.abstractapi.com/v1/}"
  api-key: "${EMAIL_VALIDATOR_API_KEY:CHANGE_ME_IN_ENV}"
  timeout: "${EMAIL_VALIDATOR_TIMEOUT:1000}" # milliseconds

# Resilience4j
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        register-health-indicator: true
    instances:
      emailValidator:
        base-config: default
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        sliding-window-size: 5
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 25s
        max-wait-duration-in-half-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: false
        record-exceptions: java.util.concurrent.TimeoutException
        ignore-exceptions: com.onclass.technology.domain.exceptions.BusinessException
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        maxWaitDuration: 10000ms
        initialInterval: 500ms
    instances:
      emailValidatorRetry:
        maxAttempts: 5
        waitDuration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
        maxWaitDuration: 10000ms
        initialInterval: 500ms
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 500ms
    instances:
      emailValidatorBulkhead:
        maxConcurrentCalls: 5
        maxWaitDuration: 1s

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.pool: INFO
